### ISSUE TITLE
If Chinese character in category then it will display fatal error

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#437]
Used Chinese characters in the category 
汉字

In the admin side on all foods page displaying a fatal error

Fatal error: Uncaught ArgumentCountError: 7 arguments are required, 1 given in C:\xampp\htdocs\tester\wp-content\plugins\wp-food-manager\includes\wpfm-action-hooks.php:267 Stack trace: #0 C:\xampp\htdocs\tester\wp-content\plugins\wp-food-manager\includes\wpfm-action-hooks.php(267): printf('<select name='f...') #1 C:\xampp\htdocs\tester\wp-includes\class-wp-hook.php(310): WPFM_ActionHooks->foods_by_category('food_manager') #2 C:\xampp\htdocs\tester\wp-includes\class-wp-hook.php(332): WP_Hook->apply_filters('', Array) #3 C:\xampp\htdocs\tester\wp-includes\plugin.php(517): WP_Hook->do_action(Array) #4 C:\xampp\htdocs\tester\wp-admin\includes\class-wp-posts-list-table.php(594): do_action('restrict_manage...', 'food_manager', 'top') #5 C:\xampp\htdocs\tester\wp-admin\includes\class-wp-list-table.php(1446): WP_Posts_List_Table->extra_tablenav('top') #6 C:\xampp\htdocs\tester\wp-admin\includes\class-wp-list-table.php(1380): WP_List_Table->display_tablenav('top') #7 C:\xampp\htdocs\tester\wp-admin\edit.php(487): WP_List_Table->display() #8 {main} thrown in C:\xampp\htdocs\tester\wp-content\plugins\wp-food-manager\includes\wpfm-action-hooks.php on line 267

![image](https://user-images.githubusercontent.com/121149500/233259429-176273fa-687c-47c1-a14d-7a351b016e57.png)

**Comment by patel-nimesh** [comment]
Now this is working fine.
